# Form implementation generated from reading ui file 'specatalog_mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1086, 811)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Knopf_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Knopf_1.setGeometry(QtCore.QRect(950, 470, 88, 25))
        self.Knopf_1.setObjectName("Knopf_1")
        self.MeasurementsView = QtWidgets.QTableView(parent=self.centralwidget)
        self.MeasurementsView.setGeometry(QtCore.QRect(40, 20, 1031, 391))
        self.MeasurementsView.setObjectName("MeasurementsView")
        self.ComboModelChoice = QtWidgets.QComboBox(parent=self.centralwidget)
        self.ComboModelChoice.setGeometry(QtCore.QRect(80, 450, 151, 25))
        self.ComboModelChoice.setObjectName("ComboModelChoice")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1086, 22))
        self.menubar.setObjectName("menubar")
        self.menuMainWindow = QtWidgets.QMenu(parent=self.menubar)
        self.menuMainWindow.setObjectName("menuMainWindow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMainWindow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Knopf_1.setText(_translate("MainWindow", "Knopf 1"))
        self.menuMainWindow.setTitle(_translate("MainWindow", "MainWindow"))
