"""add additional_info field to measurement model

Revision ID: 00555547b637
Revises: 2fef0175672b
Create Date: 2026-05-22 09:58:39.543685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00555547b637"
down_revision: Union[str, Sequence[str], None] = "2fef0175672b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "measurements", sa.Column("additional_info", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measurements", "additional_info")
    # ### end Alembic commands ###
