"""add fluorescence measurement

Revision ID: 2966fc056127
Revises: 2ff4277f3890
Create Date: 2026-01-12 13:16:11.493030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2966fc056127'
down_revision: Union[str, Sequence[str], None] = '2ff4277f3890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fluorescence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excitation', sa.Boolean(), nullable=False),
    sa.Column('excitation_wl', sa.String(length=64), nullable=False),
    sa.Column('od', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['measurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fluorescence')
    # ### end Alembic commands ###
