"""Add name_suffix

Revision ID: 2fef0175672b
Revises: c9de90733c73
Create Date: 2026-02-17 13:41:40.944939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fef0175672b'
down_revision: Union[str, Sequence[str], None] = 'c9de90733c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rp', sa.Column('name_suffix', sa.String(length=64), nullable=True))
    op.add_column('tdp', sa.Column('name_suffix', sa.String(length=64), nullable=True))
    op.add_column('ttp', sa.Column('name_suffix', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ttp', 'name_suffix')
    op.drop_column('tdp', 'name_suffix')
    op.drop_column('rp', 'name_suffix')
    # ### end Alembic commands ###
