"""add uvvis measurement

Revision ID: 2ff4277f3890
Revises: 4c002ff6dfdd
Create Date: 2025-12-19 11:41:04.411825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff4277f3890'
down_revision: Union[str, Sequence[str], None] = '4c002ff6dfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uvvis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dim_cuvette', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['measurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uvvis')
    # ### end Alembic commands ###
