"""initial schema

Revision ID: 4c002ff6dfdd
Revises: 
Create Date: 2025-12-18 10:10:09.811066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c002ff6dfdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('molecular_formula', sa.String(length=124), nullable=False),
    sa.Column('structural_formula', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('structural_formula')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('molecular_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('solvent', sa.Enum('toluene', 'water', name='solvents'), nullable=False),
    sa.Column('concentration', sa.String(length=512), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('measured_by', sa.Enum('richert', 'maylaender', 'thielert', name='names'), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('device', sa.Enum('leer', 'elexsys', 'emx_nano', name='devices'), nullable=True),
    sa.Column('series', sa.String(length=512), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('corrected', sa.Boolean(), nullable=False),
    sa.Column('evaluated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['molecular_id'], ['molecules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_measurements_molecular_id'), 'measurements', ['molecular_id'], unique=False)
    op.create_table('rp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radical_1', sa.Enum('trp', 'flav', name='radicals'), nullable=False),
    sa.Column('linker', sa.Enum('bi', 'co', 'sup_h_tz', 'xylene', name='linker'), nullable=False),
    sa.Column('radical_2', sa.Enum('trp', 'flav', name='radicals'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['molecules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('single',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['molecules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tdp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doublet', sa.Enum('no1', 'no2', 'no3', 'no4', 'no5', 'tri', name='doublets'), nullable=False),
    sa.Column('linker', sa.Enum('bi', 'co', 'sup_h_tz', 'xylene', name='linker'), nullable=False),
    sa.Column('chromophore', sa.Enum('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['molecules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ttp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triplet_1', sa.Enum('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'), nullable=False),
    sa.Column('linker', sa.Enum('bi', 'co', 'sup_h_tz', 'xylene', name='linker'), nullable=False),
    sa.Column('triplet_2', sa.Enum('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['molecules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cwepr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency_band', sa.Enum('leer', 's', 'x', 'q', 'w', name='frequencybands'), nullable=False),
    sa.Column('attenuation', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['measurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulse_epr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulse_experiment', sa.Enum('peanut', 'peldor', 'tn', 'saturation_recovery', 'esenut', name='pulseexperiments'), nullable=False),
    sa.Column('frequency_band', sa.Enum('leer', 's', 'x', 'q', 'w', name='frequencybands'), nullable=True),
    sa.Column('attenuation', sa.String(length=32), nullable=True),
    sa.Column('excitation_wl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['measurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trepr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency_band', sa.Enum('leer', 's', 'x', 'q', 'w', name='frequencybands'), nullable=False),
    sa.Column('excitation_wl', sa.Float(), nullable=False),
    sa.Column('excitation_energy', sa.Float(), nullable=True),
    sa.Column('attenuation', sa.String(length=32), nullable=False),
    sa.Column('number_of_scans', sa.Integer(), nullable=True),
    sa.Column('repetitionrate', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['measurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trepr')
    op.drop_table('pulse_epr')
    op.drop_table('cwepr')
    op.drop_table('ttp')
    op.drop_table('tdp')
    op.drop_table('single')
    op.drop_table('rp')
    op.drop_index(op.f('ix_measurements_molecular_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('molecules')
    # ### end Alembic commands ###
