"""add ta measurement

Revision ID: 6c09d149d5bb
Revises: 2966fc056127
Create Date: 2026-01-12 14:40:48.276594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c09d149d5bb'
down_revision: Union[str, Sequence[str], None] = '2966fc056127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timedomain', sa.Enum('ns', 'fs', name='timedomains'), nullable=False),
    sa.Column('excitation_energy', sa.String(length=64), nullable=False),
    sa.Column('excitation_wl', sa.String(length=64), nullable=False),
    sa.Column('od', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['measurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ta')
    # ### end Alembic commands ###
