"""Change Enum to String

Revision ID: bda9373c5357
Revises: 6c09d149d5bb
Create Date: 2026-01-22 11:06:20.528253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bda9373c5357'
down_revision: Union[str, Sequence[str], None] = '6c09d149d5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cwepr', 'frequency_band',
               existing_type=postgresql.ENUM('leer', 's', 'x', 'q', 'w', name='frequencybands'),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('measurements', 'solvent',
               existing_type=postgresql.ENUM('toluene', 'water', name='solvents'),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('measurements', 'measured_by',
               existing_type=postgresql.ENUM('richert', 'maylaender', 'thielert', name='names'),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('measurements', 'device',
               existing_type=postgresql.ENUM('leer', 'elexsys', 'emx_nano', name='devices'),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('pulse_epr', 'pulse_experiment',
               existing_type=postgresql.ENUM('peanut', 'peldor', 'tn', 'saturation_recovery', 'esenut', name='pulseexperiments'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('pulse_epr', 'frequency_band',
               existing_type=postgresql.ENUM('leer', 's', 'x', 'q', 'w', name='frequencybands'),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('rp', 'radical_1',
               existing_type=postgresql.ENUM('trp', 'flav', name='radicals'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('rp', 'linker',
               existing_type=postgresql.ENUM('bi', 'co', 'sup_h_tz', 'xylene', name='linker'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('rp', 'radical_2',
               existing_type=postgresql.ENUM('trp', 'flav', name='radicals'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('ta', 'timedomain',
               existing_type=postgresql.ENUM('ns', 'fs', name='timedomains'),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('tdp', 'doublet',
               existing_type=postgresql.ENUM('no1', 'no2', 'no3', 'no4', 'no5', 'tri', name='doublets'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('tdp', 'linker',
               existing_type=postgresql.ENUM('bi', 'co', 'sup_h_tz', 'xylene', name='linker'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('tdp', 'chromophore',
               existing_type=postgresql.ENUM('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('trepr', 'frequency_band',
               existing_type=postgresql.ENUM('leer', 's', 'x', 'q', 'w', name='frequencybands'),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('ttp', 'triplet_1',
               existing_type=postgresql.ENUM('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('ttp', 'linker',
               existing_type=postgresql.ENUM('bi', 'co', 'sup_h_tz', 'xylene', name='linker'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('ttp', 'triplet_2',
               existing_type=postgresql.ENUM('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ttp', 'triplet_2',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'),
               existing_nullable=False)
    op.alter_column('ttp', 'linker',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('bi', 'co', 'sup_h_tz', 'xylene', name='linker'),
               existing_nullable=False)
    op.alter_column('ttp', 'triplet_1',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'),
               existing_nullable=False)
    op.alter_column('trepr', 'frequency_band',
               existing_type=sa.String(length=16),
               type_=postgresql.ENUM('leer', 's', 'x', 'q', 'w', name='frequencybands'),
               existing_nullable=False)
    op.alter_column('tdp', 'chromophore',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('bdp0', 'bdp1', 'ndi0', 'pent', 'per', 'pdi0', 'pdi2', 'pdi4', 'por0', 'por1', 'por2', name='chromophores'),
               existing_nullable=False)
    op.alter_column('tdp', 'linker',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('bi', 'co', 'sup_h_tz', 'xylene', name='linker'),
               existing_nullable=False)
    op.alter_column('tdp', 'doublet',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('no1', 'no2', 'no3', 'no4', 'no5', 'tri', name='doublets'),
               existing_nullable=False)
    op.alter_column('ta', 'timedomain',
               existing_type=sa.String(length=16),
               type_=postgresql.ENUM('ns', 'fs', name='timedomains'),
               existing_nullable=False)
    op.alter_column('rp', 'radical_2',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('trp', 'flav', name='radicals'),
               existing_nullable=False)
    op.alter_column('rp', 'linker',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('bi', 'co', 'sup_h_tz', 'xylene', name='linker'),
               existing_nullable=False)
    op.alter_column('rp', 'radical_1',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('trp', 'flav', name='radicals'),
               existing_nullable=False)
    op.alter_column('pulse_epr', 'frequency_band',
               existing_type=sa.String(length=16),
               type_=postgresql.ENUM('leer', 's', 'x', 'q', 'w', name='frequencybands'),
               existing_nullable=True)
    op.alter_column('pulse_epr', 'pulse_experiment',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('peanut', 'peldor', 'tn', 'saturation_recovery', 'esenut', name='pulseexperiments'),
               existing_nullable=False)
    op.alter_column('measurements', 'device',
               existing_type=sa.String(length=512),
               type_=postgresql.ENUM('leer', 'elexsys', 'emx_nano', name='devices'),
               existing_nullable=True)
    op.alter_column('measurements', 'measured_by',
               existing_type=sa.String(length=512),
               type_=postgresql.ENUM('richert', 'maylaender', 'thielert', name='names'),
               existing_nullable=False)
    op.alter_column('measurements', 'solvent',
               existing_type=sa.String(length=512),
               type_=postgresql.ENUM('toluene', 'water', name='solvents'),
               existing_nullable=False)
    op.alter_column('cwepr', 'frequency_band',
               existing_type=sa.String(length=16),
               type_=postgresql.ENUM('leer', 's', 'x', 'q', 'w', name='frequencybands'),
               existing_nullable=False)
    # ### end Alembic commands ###
