"""Change molecular_formula to optional, move additional_info to MoleculeModel

Revision ID: c9de90733c73
Revises: bda9373c5357
Create Date: 2026-02-17 13:30:18.082796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9de90733c73'
down_revision: Union[str, Sequence[str], None] = 'bda9373c5357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('molecules', sa.Column('additional_info', sa.Text(), nullable=True))
    op.alter_column('molecules', 'molecular_formula',
               existing_type=sa.VARCHAR(length=124),
               nullable=True)
    op.drop_column('single', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single', sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('molecules', 'molecular_formula',
               existing_type=sa.VARCHAR(length=124),
               nullable=False)
    op.drop_column('molecules', 'additional_info')
    # ### end Alembic commands ###
